// Default clean and comprehensive dataset for system reset
export const DEFAULT_HOTEL_DATA = {
  hotelSettings: {
    hotelName: "فندق قصر الضيافة الملكي - خدر ليالي الأنس",
    hotelSubtitle: "نظام الإدارة الفندقية، الغرف، والوفود الرسمية",
    registrationLinkStatus: "open",
    activeDatabase: "cloudsql_and_supabase",
    contactPhone: "+966 11 456 7890",
    receptionMobile: "+966 50 123 4567",
    receptionEmail: "reception@layali-aluns.com",
    address: "المملكة العربية السعودية - الرياض - طريق الملك فهد",
    currentYear: "2026",
    defaultVisitType: "general_1",
    primaryColor: "#1e3a8a",
    updatedAt: new Date().toISOString()
  },
  rooms: [
    // الطابق الأول (Floor 1)
    {
      id: "room_101",
      number: "101",
      name: "جناح اليمامة الملكي",
      floor: 1,
      type: "جناح ملكي (Royal Suite)",
      capacity: 4,
      status: "occupied",
      direction: "إطلالة بحرية بانورامية",
      pricePerNight: 1500,
      features: ["جاكوزي خاص", "مجلس ضيافة مستقل", "ماكينة قهوة مختصة", "شاشة 75 بوصة ذكية", "خدمة كونسيرج 24/7", "واي فاي 6 فائق السرعة"],
      notes: "مخصص لإقامة رئيس الوفد الرسمي"
    },
    {
      id: "room_102",
      number: "102",
      name: "غرفة الياسمين التنفيذية",
      floor: 1,
      type: "غرفة مزدوجة فاخرة (Double)",
      capacity: 2,
      status: "available",
      direction: "إطلالة على المسبح والحديقة",
      pricePerNight: 650,
      features: ["سرير كينج فندقي", "مكتب عمل مجهز", "شاشة 55 بوصة", "ثلاجة وميني بار", "شرفة خاصة"],
      notes: "جاهزة للاستقبال الفوري"
    },
    {
      id: "room_103",
      number: "103",
      name: "غرفة النرجس الهادئة",
      floor: 1,
      type: "غرفة مفردة (Single)",
      capacity: 1,
      status: "available",
      direction: "إطلالة داخلية هادئة",
      pricePerNight: 400,
      features: ["سرير مفرد وثير", "إنترنت فائق السرعة", "حمام رخامي", "شاشة ذكية 43 بوصة"],
      notes: "غرفة هادئة مناسبة للأفراد"
    },
    {
      id: "room_104",
      number: "104",
      name: "غرفة الريحان المزدوجة",
      floor: 1,
      type: "غرفة مزدوجة فاخرة (Double)",
      capacity: 2,
      status: "cleaning",
      direction: "إطلالة على الحديقة",
      pricePerNight: 600,
      features: ["سريران منفصلان", "جلسة قهوة مريحة", "شرفة خاصة", "تلفزيون ذكي"],
      notes: "جاري التنظيف والتجهيز حالياً"
    },

    // الطابق الثاني (Floor 2)
    {
      id: "room_201",
      number: "201",
      name: "جناح الريان العائلي",
      floor: 2,
      type: "جناح عائلي (Family Suite)",
      capacity: 6,
      status: "available",
      direction: "إطلالة على المدينة والحديقة",
      pricePerNight: 1200,
      features: ["غرفتا نوم متصلتان", "صالة جلوس عائلية واسعة", "طاولة طعام", "مطبخ تحضيري مصغر", "حمامان فاخران"],
      notes: "مثالي للعائلات والوفود المرافقة"
    },
    {
      id: "room_202",
      number: "202",
      name: "غرفة النخيل الدافئة",
      floor: 2,
      type: "غرفة مزدوجة فاخرة (Double)",
      capacity: 2,
      status: "occupied",
      direction: "إطلالة بحرية",
      pricePerNight: 700,
      features: ["إطلالة بحرية ساحرة", "سرير كينج كبير", "روب وحمام رخامي", "بار مشروبات ساخنة وباردة"],
      notes: "مخصصة لنائب رئيس الوفد"
    },
    {
      id: "room_203",
      number: "203",
      name: "غرفة السدرة البسيطة",
      floor: 2,
      type: "غرفة مفردة (Single)",
      capacity: 1,
      status: "available",
      direction: "إطلالة على المدينة",
      pricePerNight: 420,
      features: ["مكتب مريح للعمل", "واي فاي سريع", "خدمة إفطار بالغرفة", "خزنة أمانات إلكترونية"],
      notes: "جاهزة ومجهزة بالكامل"
    },
    {
      id: "room_204",
      number: "204",
      name: "جناح الكوثر التنفيذي",
      floor: 2,
      type: "جناح تنفيذي (Executive Suite)",
      capacity: 3,
      status: "available",
      direction: "إطلالة مسبح",
      pricePerNight: 950,
      features: ["غرفة نوم رئيسية", "صالة استقبال أنيقة", "ماكينة قهوة نسبريسو", "شاشة 65 بوصة 4K"],
      notes: "جناح راقي مناسب لرجال الأعمال"
    },

    // الطابق الثالث (Floor 3)
    {
      id: "room_301",
      number: "301",
      name: "جناح الأندلس الفخم (VIP)",
      floor: 3,
      type: "جناح ملكي (Royal Suite)",
      capacity: 4,
      status: "occupied",
      direction: "إطلالة بحرية مباشرة",
      pricePerNight: 2000,
      features: ["مدخل خاص لكبار الضيوف", "مجلس شرف VIP", "غرفة نوم ماستر ملكية", "حمام جاكوزي بانورامي", "خدمة خادم شخصي"],
      notes: "مخصص لإقامة ضيف الشرف الدبلوماسي"
    },
    {
      id: "room_302",
      number: "302",
      name: "غرفة الفيروز المطلة",
      floor: 3,
      type: "غرفة مزدوجة فاخرة (Double)",
      capacity: 2,
      status: "available",
      direction: "إطلالة على المسبح",
      pricePerNight: 680,
      features: ["سريران منفصلان فندقيان", "شرفة واسعة", "واي فاي غير محدود", "عوازل صوتية متطورة"],
      notes: "جاهزة للإشغال"
    },
    {
      id: "room_303",
      number: "303",
      name: "غرفة المرجان الكلاسيكية",
      floor: 3,
      type: "غرفة مفردة (Single)",
      capacity: 1,
      status: "maintenance",
      direction: "إطلالة داخلية",
      pricePerNight: 400,
      features: ["سرير مفرد عالي الجودة", "نظام تكييف ذكي", "صندوق أمانات إلكتروني"],
      notes: "صيانة دورية للأجهزة الكهربائية"
    },
    {
      id: "room_304",
      number: "304",
      name: "غرفة العقيق المزدوجة",
      floor: 3,
      type: "غرفة مزدوجة فاخرة (Double)",
      capacity: 2,
      status: "available",
      direction: "إطلالة بحرية",
      pricePerNight: 720,
      features: ["إطلالة بحرية مباشرة", "سرير كينج فاخر", "ماكينة قهوة", "شاشة 55 بوصة"],
      notes: "غرفة راقية بإطلالة متميزة"
    },

    // الطابق الرابع (Floor 4)
    {
      id: "room_401",
      number: "401",
      name: "جناح القمة البانورامي",
      floor: 4,
      type: "جناح ملكي (Royal Suite)",
      capacity: 4,
      status: "available",
      direction: "إطلالة بانورامية كاملة 360",
      pricePerNight: 1800,
      features: ["إطلالة زجاجية مفتوحة", "صالة اجتماعات مصغرة", "مكتب عمل VIP", "شاشات عرض ذكية", "جاكوزي مطل"],
      notes: "أعلى درجات الفخامة مع رؤية واسعة"
    },
    {
      id: "room_402",
      number: "402",
      name: "غرفة الزمرد التنفيذية",
      floor: 4,
      type: "غرفة مزدوجة فاخرة (Double)",
      capacity: 2,
      status: "occupied",
      direction: "إطلالة على المدينة",
      pricePerNight: 750,
      features: ["سرير كينج فخم", "ركن قهوة فاخر", "مكتب دراسة متطور", "خدمة كي سريعة"],
      notes: "إقامة المستشار الإداري للوفد"
    },
    {
      id: "room_403",
      number: "403",
      name: "غرفة اللؤلؤ الهادئة",
      floor: 4,
      type: "غرفة مفردة (Single)",
      capacity: 1,
      status: "available",
      direction: "إطلالة داخلية",
      pricePerNight: 450,
      features: ["سرير مفرد وثير", "إطلالة بحرية جزئية", "تجهيزات فندقية 5 نجوم"],
      notes: "جاهزة للإشغال"
    },
    {
      id: "room_404",
      number: "404",
      name: "جناح دلمون الدبلوماسي",
      floor: 4,
      type: "جناح تنفيذي (Executive Suite)",
      capacity: 3,
      status: "available",
      direction: "إطلالة بحرية",
      pricePerNight: 1400,
      features: ["صالة استقبال دبلوماسية", "تجهيزات أمان متقدمة", "شاشة سينمائية", "بوفيه ضيافة مجهز"],
      notes: "مجهز للوفود الدبلوماسية"
    },

    // الطابق الخامس (Floor 5 - Penthouse & Royal)
    {
      id: "room_501",
      number: "501",
      name: "جناح الخزامى الإمبراطوري",
      floor: 5,
      type: "جناح إمبراطوري (Imperial Suite)",
      capacity: 5,
      status: "available",
      direction: "إطلالة بانورامية بحرية وأفق المدينة",
      pricePerNight: 2800,
      features: ["تراس خارجي خاص مع جاكوزي معلق", "صالة طعام رسمية لـ 8 أشخاص", "مصعد خاص مباشر", "خادم شخصي خاص"],
      notes: "الجناح الرئاسي الأعلى في الفندق"
    },
    {
      id: "room_502",
      number: "502",
      name: "غرفة الأوركيد الفاخرة",
      floor: 5,
      type: "غرفة مزدوجة فاخرة (Double)",
      capacity: 2,
      status: "available",
      direction: "إطلالة على أفق المدينة",
      pricePerNight: 850,
      features: ["سرير كينج مصمم", "إضاءة مزاجية ذكية", "نظام صوتي محيطي", "شرفة بإطلالة علوية"],
      notes: "طابق كبار الضيوف VIP"
    }
  ],

  guests: [
    {
      id: "G-101",
      name: "د. عبد الرحمن بن فهد الشمري",
      country: "المملكة العربية السعودية",
      mobile: "+966501234567",
      whatsapp: "+966501234567",
      email: "dr.shammary@delegation.gov.sa",
      roomNumber: "101",
      status: "resident",
      administrativeRole: "رئيس الوفد",
      visitType: "general_1",
      year: "2026",
      checkInDate: "2026-09-15",
      checkOutDate: "2026-09-26",
      photoUrl: "",
      nationalId: "1087452319",
      qrCode: "GUEST-G-101-ROOM-101",
      notes: "رئيس الوفد الرسمي - ضيافة ملكية خاصة وخدمة كونسيرج 24/7"
    },
    {
      id: "G-202",
      name: "م. طارق بن خالد المنصور",
      country: "دولة الكويت",
      mobile: "+96599887766",
      whatsapp: "+96599887766",
      email: "t.almansour@kuwait-gov.kw",
      roomNumber: "202",
      status: "resident",
      administrativeRole: "نائب رئيس الوفد",
      visitType: "general_1",
      year: "2026",
      checkInDate: "2026-09-16",
      checkOutDate: "2026-09-24",
      photoUrl: "",
      nationalId: "285091204581",
      qrCode: "GUEST-G-202-ROOM-202",
      notes: "منسق إداري وعضو اللجنة العليا المشتركة"
    },
    {
      id: "G-301",
      name: "سعادة السفير ياسر عبد الله القحطاني",
      country: "الإمارات العربية المتحدة",
      mobile: "+971501122334",
      whatsapp: "+971501122334",
      email: "yasser.qahtani@mofa.gov.ae",
      roomNumber: "301",
      status: "resident",
      administrativeRole: "ضيف شرف (VIP)",
      visitType: "general_1",
      year: "2026",
      checkInDate: "2026-09-16",
      checkOutDate: "2026-09-25",
      photoUrl: "",
      nationalId: "784-1980-1234567-1",
      qrCode: "GUEST-G-301-ROOM-301",
      notes: "استقبال كبار الشخصيات والوفود الدبلوماسية مع موكب خاص"
    },
    {
      id: "G-402",
      name: "أ. فيصل بن سلطان الهاجري",
      country: "دولة قطر",
      mobile: "+97455667788",
      whatsapp: "+97455667788",
      email: "f.alhajri@delegation.qa",
      roomNumber: "402",
      status: "resident",
      administrativeRole: "مستشار إداري",
      visitType: "general_1",
      year: "2026",
      checkInDate: "2026-09-17",
      checkOutDate: "2026-09-23",
      photoUrl: "",
      nationalId: "28663400192",
      qrCode: "GUEST-G-402-ROOM-402",
      notes: "مستشار التخطيط الاستراتيجي والعلاقات العامة"
    }
  ],

  serviceRequests: [
    {
      id: "srv_1",
      roomNumber: "101",
      guestName: "د. عبد الرحمن بن فهد الشمري",
      guestMobile: "+966501234567",
      serviceType: "ضيافة واستقبال VIP",
      details: "تجهيز دلال القهوة والشاي والتمر السكري الفاخر للجناح الملكي",
      status: "completed",
      createdAt: "2026-09-16T10:00:00.000Z",
      completedAt: "2026-09-16T10:35:00.000Z",
      year: "2026",
      visitType: "general_1"
    },
    {
      id: "srv_2",
      roomNumber: "202",
      guestName: "م. طارق بن خالد المنصور",
      guestMobile: "+96599887766",
      serviceType: "خدمة تنظيف وتجهيز الغرفة",
      details: "تجديد المفارش والمناشف والمستلزمات الفندقية وتجهيز الملابس للكي",
      status: "in_progress",
      createdAt: "2026-09-17T08:30:00.000Z",
      completedAt: null,
      year: "2026",
      visitType: "general_1"
    },
    {
      id: "srv_3",
      roomNumber: "301",
      guestName: "سعادة السفير ياسر عبد الله القحطاني",
      guestMobile: "+971501122334",
      serviceType: "خدمات كونسيرج ونقل VIP",
      details: "تنسيق سيارة خاصة مع سائق لمرافقة الوفد لحضور الاجتماع الرسمي",
      status: "in_progress",
      createdAt: "2026-09-17T11:15:00.000Z",
      completedAt: null,
      year: "2026",
      visitType: "general_1"
    },
    {
      id: "srv_4",
      roomNumber: "402",
      guestName: "أ. فيصل بن سلطان الهاجري",
      guestMobile: "+97455667788",
      serviceType: "دعم فني وتقني",
      details: "فحص شاشة العرض والاتصال اللاسلكي المباشر بقاعة الاجتماعات",
      status: "pending",
      createdAt: "2026-09-17T14:00:00.000Z",
      completedAt: null,
      year: "2026",
      visitType: "general_1"
    }
  ],

  pendingRequests: [
    {
      id: "req_101",
      name: "م. عادل بن محمد الحربي",
      country: "المملكة العربية السعودية",
      mobile: "+966554321987",
      email: "adel.harbi@saudi-eng.sa",
      whatsapp: "+966554321987",
      roomType: "غرفة مزدوجة فاخرة (Double)",
      status: "pending",
      checkInDate: "2026-09-22",
      checkOutDate: "2026-09-28",
      companionsCount: 1,
      administrativeRole: "عضو وفد",
      notes: "حضور مؤتمر التقنية والإدارة الفندقية المشتركة",
      year: "2026",
      visitType: "general_1",
      createdAt: "2026-09-17T09:00:00.000Z"
    },
    {
      id: "req_102",
      name: "د. نورة بنت سعد الدوسري",
      country: "المملكة العربية السعودية",
      mobile: "+966509876543",
      email: "noura.dossary@university.edu.sa",
      whatsapp: "+966509876543",
      roomType: "جناح تنفيذي (Executive Suite)",
      status: "pending",
      checkInDate: "2026-09-23",
      checkOutDate: "2026-09-27",
      companionsCount: 0,
      administrativeRole: "مستشار إداري",
      notes: "مشاركة كمتحدثة رئيسية في الجلسة الافتتاحية",
      year: "2026",
      visitType: "general_1",
      createdAt: "2026-09-17T10:45:00.000Z"
    },
    {
      id: "req_103",
      name: "أ. بدر ناصر الصباح",
      country: "دولة الكويت",
      mobile: "+96594321098",
      email: "bader.sabah@business.kw",
      whatsapp: "+96594321098",
      roomType: "جناح عائلي (Family Suite)",
      status: "pending",
      checkInDate: "2026-09-24",
      checkOutDate: "2026-09-30",
      companionsCount: 3,
      administrativeRole: "ضيف شرف (VIP)",
      notes: "حجز مسبق مع توفير سرير أطفال إضافي في الجناح",
      year: "2026",
      visitType: "general_1",
      createdAt: "2026-09-17T13:20:00.000Z"
    }
  ],

  gateLogs: [
    {
      id: "gate_1",
      guestId: "G-101",
      guestName: "د. عبد الرحمن بن فهد الشمري",
      roomNumber: "101",
      entryType: "دخول",
      gateName: "البوابة الرئيسية",
      timestamp: "2026-09-17T09:15:00.000Z",
      officerName: "أحمد السعيد",
      notes: "دخول رسمي مع موكب الوفد"
    },
    {
      id: "gate_2",
      guestId: "G-301",
      guestName: "سعادة السفير ياسر عبد الله القحطاني",
      roomNumber: "301",
      entryType: "دخول",
      gateName: "بوابة VIP الخاصة",
      timestamp: "2026-09-17T11:30:00.000Z",
      officerName: "خالد العتيبي",
      notes: "استقبال شرفي ومرافقة أمنية"
    },
    {
      id: "gate_3",
      guestId: "G-202",
      guestName: "م. طارق بن خالد المنصور",
      roomNumber: "202",
      entryType: "خروج",
      gateName: "البوابة الشرقية",
      timestamp: "2026-09-17T14:10:00.000Z",
      officerName: "فهد الزهراني",
      notes: "خروج لحضور اجتماع خارجي رسمي"
    },
    {
      id: "gate_4",
      guestId: "G-402",
      guestName: "أ. فيصل بن سلطان الهاجري",
      roomNumber: "402",
      entryType: "دخول",
      gateName: "البوابة الرئيسية",
      timestamp: "2026-09-17T16:45:00.000Z",
      officerName: "أحمد السعيد",
      notes: "عودة من الجولة المسائية"
    }
  ]
};
